# Generated by Django 6.0.2 on 2026-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcontacto',
            name='leido',
        ),
        migrations.AddField(
            model_name='leadcontacto',
            name='redes_sociales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
